### ISSUE TITLE
Question: LinTS takes a hours to run

### ISSUE THREAD

**Issue by lenagangan** [st-tech/zr-obp#3]
Hello, first of all, thanks for the paper, it is really helpful. Just wanted to make sure that this is the expected behavior: LinTS takes >3h to run on the random/all big dataset (>1mln items. cpu only). Is this the expected behavior? Thank you!

**Comment by usaito** [comment]
Thank you for your interest in our project! Yes, that is expected behavior.

We've just released version 0.3.0 of the package. In this new version, we changed the way we implement the example analysis with the pipeline to make the analysis more consistent with the theoretical formulation of OPE. Specifically, we use offline bandit policies (not the online ones including LinTS) in the new examples: https://github.com/st-tech/zr-obp/tree/master/examples.

A corresponding update of the paper will come soon..., so please join our google group below to follow some coming updates!
https://groups.google.com/g/open-bandit-project

**Comment by lenagangan** [comment]
Great! Thank you. Closing
