### ISSUE TITLE
Replay method allows only deterministic policies

### ISSUE THREAD

**Issue by nmasahiro** [st-tech/zr-obp#46]
The current implementation of the replay method seems to allow only deterministic policies.
https://github.com/st-tech/zr-obp/blob/55ab57ea214db3e69550e48c466ca8d52074145e/obp/ope/estimators.py#L93-L95

If it needs to fix it, I will make a pull requrest about the replay method that also allows stochastic policy.

**Comment by usaito** [comment]
@nmasahiro 

It's the expected behavior given that we use simulator module when using the replay method.
You can also refer to algorithm 2 of https://arxiv.org/pdf/1003.5956.pdf for this.

Kuroiwa-san with implement some examples about offline evaluation of online bandit algorithms using the replay method later!

**Comment by nmasahiro** [comment]
I understand. Thanks!
